### ISSUE TITLE
Design the About Us page

### ISSUE THREAD

**Issue by jay24rajput** [NJACKWinterOfCode/onRoad#15]
The current About Us Page is just a toast message. Add an activity to the page for displaying relevant info like the developers list, etc.

**Comment by thebishaldeb** [comment]
Add details about the app in the page. You may take help from the Readme as you want.

**Comment by pavitrawalia** [comment]
@thebishaldeb Can I take up this issue?

**Comment by thebishaldeb** [comment]
Assigned

**Comment by pavitrawalia** [comment]
@thebishaldeb I have attached the screenshot of the sample about us page . Please have a look here .
![WhatsApp Image 2019-12-05 at 3 55 03 PM](https://user-images.githubusercontent.com/30498337/70227409-8bf7ab00-1778-11ea-807b-fae9da863d9c.jpeg)
What else should be included in the about us page?

**Comment by thebishaldeb** [comment]
The logo that is being used currently. Also, a li'l designing. THe page looks blank and doesn't catch eye.

**Comment by pavitrawalia** [comment]
Any other content related thing that must be displayed on this page ?

**Comment by thebishaldeb** [comment]
For now it is fine. Can be added as and when needed later.

**Comment by thebishaldeb** [comment]
Update?

**Comment by pavitrawalia** [comment]
@thebishaldeb It's almost complete. will share the updated page by tomorrow.

**Comment by pavitrawalia** [comment]
![IMG-20191211-WA0032](https://user-images.githubusercontent.com/30498337/70618539-26546480-1c39-11ea-99dd-0cf58f4b9542.jpg)
@thebishaldeb  Is this looking okay for now?

**Comment by thebishaldeb** [comment]
Cool enough.

**Comment by pavitrawalia** [comment]
@thebishaldeb I have created a pull request referring to this issue here.
[https://github.com/NJACKWinterOfCode/onRoad/pull/33](url)
