### ISSUE TITLE
Add Facebook Signin

### ISSUE THREAD

**Issue by thebishaldeb** [NJACKWinterOfCode/onRoad#17]
Sign in using facebook from firebase.

**Comment by Sarthak2601** [comment]
Working on it.

**Comment by VikasPandey121** [comment]
@thebishaldeb  I would like to work on it as I am familiar with this issue.

**Comment by thebishaldeb** [comment]
@VikasPandey121  @Sarthak2601 commented on it first. Try a different one maybe.

**Comment by thebishaldeb** [comment]
@VikasPandey121 you may work on it if you want!

**Comment by VikasPandey121** [comment]
Yes, I would love to. Assign this issue to me. 


**Thank you**

**Comment by Sarthak2601** [comment]
@thebishaldeb but I am working on it.

**Comment by thebishaldeb** [comment]
@VikasPandey121 you may do the other one assigned to you since he's working on it.

**Comment by VikasPandey121** [comment]
@thebishaldeb sorry to say but it is unfortunate that you are creating conflicts for this issue. It would be appreciable if you would have consulted @Sarthak2601 before asking, assigning and unassigning me.

**Comment by VikasPandey121** [comment]
@thebishaldeb You are following the best practice of open-source.
