### ISSUE TITLE
Email verification

### ISSUE THREAD

**Issue by thebishaldeb** [NJACKWinterOfCode/onRoad#18]
Verification of the emailm then only can the user sign in.

**Comment by Sarthak2601** [comment]
Working on it.

**Comment by thebishaldeb** [comment]
Update?

**Comment by Sarthak2601** [comment]
@thebishaldeb Would like to talk to you about this issue on Gitter.

**Comment by thebishaldeb** [comment]
> @thebishaldeb Would like to talk to you about this issue on Gitter.

Sure

**Comment by VARUN12KUMAR** [comment]
can i work on this??

**Comment by thebishaldeb** [comment]
Assigned it to you @VARUN12KUMAR

**Comment by thebishaldeb** [comment]
Update?

**Comment by s-ayush2903** [comment]
@thebishaldeb I am fixing it!!!
