### ISSUE TITLE
Keyboard not hiding automatically neither in MainActivity, UseAsDriver Activity and UseAsRider Activity

### ISSUE THREAD

**Issue by VikasPandey121** [NJACKWinterOfCode/onRoad#25]
## Summary

Keyboard not hiding automatically neither in MainActivity, UseAsDriver Activity and UseAsRider Activity

## Expected behaviour 

Whenever the user taps on the Parent Layout of any Activity, the keyboard should hide automatically.

## Observed behaviour 
Keyboard not hiding automatically neither in MainActivity, UseAsDriver Activity and UseAsRider Activity which is being the cause minimisation of screen accessibility once the keyboard is opened.

### MainActivity

<img src = "https://raw.githubusercontent.com/VikasPandey121/Reported-issues/master/supportingFiles/Issues/MainActivity.gif">

### UseAsDriver Activity

<img src = "https://raw.githubusercontent.com/VikasPandey121/Reported-issues/master/supportingFiles/Issues/UseAsDriver.gif">

### UseAsRider Activity

<img src = "https://raw.githubusercontent.com/VikasPandey121/Reported-issues/master/supportingFiles/Issues/UseAsRider.gif">

## Would you like to work on this issue?

 - Yes, I would like to work on this issue.

**Comment by thebishaldeb** [comment]
Update?

**Comment by VikasPandey121** [comment]
I will surely work on it. Just to minimise conflicts, I have not started working on it as it is not assigned me yet.

**Comment by VikasPandey121** [comment]
Please assign me this issue.

**Thank You**

**Comment by thebishaldeb** [comment]
Update?

**Comment by VikasPandey121** [comment]
Working on it

**Comment by refactor-droidyy** [comment]
@thebishaldeb can I work in this issue?

**Comment by thebishaldeb** [comment]
Update?
