### ISSUE TITLE
Add your own google-services.json

### ISSUE THREAD

**Issue by thebishaldeb** [NJACKWinterOfCode/onRoad#26]
Add your own google-services.json by creating a project in firebase to have access to your database to work on it.

Don't commit that file in the repo to avoid conflicts.

Update README for new people to follow the steps to do the same.

**Comment by jay24rajput** [comment]
Could we just add the file to .gitignore?? Then there won't be any conflicts.

**Comment by thebishaldeb** [comment]
> Could we just add the file to .gitignore?? Then there won't be any conflicts.

Yeah something like that. And also update the readme for new people to follow the same.

**Comment by jay24rajput** [comment]
Okay I am on it!

**Comment by thebishaldeb** [comment]
Update?

**Comment by jay24rajput** [comment]
Sorry for the delay. Please have a look at the PR
