### ISSUE TITLE
Need improvement in existing UI of search ride activity

### ISSUE THREAD

**Issue by sg28march** [NJACKWinterOfCode/onRoad#28]
**changes Needed**
1.font color is white which is not visible to the user 
2.UI improvement is needed 

**Present UI**
![Screenshot_2019-12-04-17-51-51-147_com bdp onroad](https://user-images.githubusercontent.com/52504382/70143083-bc7c0e00-16c0-11ea-833b-20ad606bd598.jpg)

@thebishaldeb  Can I work on this issue?

**Comment by thebishaldeb** [comment]
Sure go ahead.

**Comment by sg28march** [comment]
> Sure go ahead.
Please review
The pull request which fixes this issue #30
