### ISSUE TITLE
A better colour scheme for the app. 

### ISSUE THREAD

**Issue by Sarthak2601** [NJACKWinterOfCode/onRoad#8]

**Comment by VikasPandey121** [comment]
I would like to work on it.

**Comment by thebishaldeb** [comment]
@VikasPandey121 go ahead. Please keep the colors consistent for all screens.

**Comment by pavitrawalia** [comment]
@thebishaldeb Can i work on this ?

**Comment by thebishaldeb** [comment]
@pavitrawalia I did not get the notification of your comment. Still interested in doing it?

**Comment by pavitrawalia** [comment]
Yes I am up for the task @thebishaldeb

**Comment by thebishaldeb** [comment]
update?
