### ISSUE TITLE
Profile view for the user.

### ISSUE THREAD

**Issue by Sarthak2601** [NJACKWinterOfCode/onRoad#9]
Currently the user has no profile

**Comment by jay24rajput** [comment]
Hey! Can I work on this issue??

**Comment by thebishaldeb** [comment]
> Hey! Can I work on this issue??

Yes you may.

**Comment by jay24rajput** [comment]
Alright! Will issue the PR

**Comment by Sarthak2601** [comment]
Can I work on this issue?

**Comment by thebishaldeb** [comment]
Cool. A person should be able to edit his profile as well. There should be fields like firstname, lastname, birthdate and username and he should be able to edit it.
